name: Build node images

on:
  schedule:
    - cron: "1 1 1 * *"
  push:
    branches: ["main"]

jobs:
  node:
    runs-on: ubuntu-latest
    environment: docker.io
    strategy:
      matrix:
        node: [20, 22, lts]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
          file: ./node/Dockerfile
          push: true
          tags: fullpipe/node:${{ matrix.node }}
          build-args: NODE_VERSION=${{ matrix.node }}
